### ISSUE TITLE
run sumulator report No such file or directory: 'array/get_reward.npy'

### ISSUE THREAD

**Issue by zouzhongy** [qq456cvb/doudizhu-C#12]
I run the sumulator/main and get same error 
1."No such file or directory: 'array/get_reward.npy'" 
2."no dir photo"
2."no dir video"
could you give us a readme or something other to help us run sumulator ?
thinks very much!!!!

**Comment by qq456cvb** [comment]
Sorry for the late reply. Actually, these arrays are used to do a template matching in order to find correponding buttons to click. It seems that some array files are missing and I will upload them from my local files. For ' no dir photo/video', you just need to create a directory called 'photo/video', which are used for visualization/debugging.
